#NAME: Dhruv Singhania
#EMAIL: singhania_dhruv@yahoo.com
#ID: 105125631

default:
	gcc -g -Wall -Wextra -o lab1a lab1a.c
clean:
	rm lab1a lab1a-105125631.tar.gz
dist:
	tar -cvzf lab1a-105125631.tar.gz lab1a.c README Makefile
