#NAME: Shrenik Manoj Kankaria,Dhruv Singhania
#EMAIL: shrenik0123@gmail.com,singhania_dhruv@yahoo.com
#ID: 005176857,105125631

default:
	rm -f lab3b
	ln lab3b_maker lab3b
	chmod u+x lab3b

clean:
	rm -f lab3b-105125631.tar.gz lab3b

dist:
	tar -czvf lab3b-105125631.tar.gz lab3b.py README Makefile lab3b_maker
