#NAME: Shrenik Manoj Kankaria,Dhruv Singhania
#EMAIL: shrenik0123@gmail.com,singhania_dhruv@yahoo.com
#ID: 005176857,105125631

default:
	gcc -o lab3a -g -Wall -Wextra lab3a.c

dist:
	tar -czvf lab3a-105125631.tar.gz lab3a.c README Makefile ext2_fs.h

clean:
	rm -f lab3a lab3a-105125631.tar.gz
