#NAME: Shrenik Manoj Kankaria,Dhruv Singhania
#EMAIL: shrenik0123@gmail.com,singhania_dhruv@yahoo.com
#ID: 005176857,105125631

.SILENT:

default:
	gcc -g -Wall -Wextra -o lab3a lab3a.c

dist:
	tar -cvzf lab3a-005176857.tar.gz ext2_fs.h README lab3a.c Makefile

clean:
	rm -f lab3a-005176857.tar.gz lab3a
