#NAME: Dhruv Singhania
#EMAIL: singhania_dhruv@yahoo.com
#ID: 105125631

dist:
	tar -cvzf lab4a-105125631.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png README Makefile

clean:
	rm lab4a-105125631.tar.gz
