#NAME: Dhruv Singhania
#EMAIL: singhania_dhruv@yahoo.com
#ID: 105125631

default:
	gcc -g -Wall -Wextra -o lab0 lab0.c

clean:
	rm lab0 lab0-105125631.tar.gz

dist:
	tar -cvzf lab0-105125631.tar.gz lab0.c README Makefile backtrace.png breakpoint.png smoke_test.sh

check:
	./smoke_test.sh
